In [1]:
import numpy as np

In [2]:
# 1.- Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

arr1 = np.random.randint (10, 100, 50)

In [6]:
arr1 = np.arange (10, 100, 5)

In [7]:
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
# 2.- Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [10]:
arr2 = np.random.randint (1, 21, 30)

In [11]:
arr2

array([ 7, 13,  4, 17, 17, 11,  1, 12,  9,  2,  5,  6, 16, 18,  5,  8,  8,
        2, 15,  5, 14, 15, 15, 16, 19,  7,  1,  8, 17, 18])

In [ ]:
impares = arr2 [::2]

In [19]:
impares

array([ 7,  4, 17,  1,  9,  5, 16,  5,  8, 15, 14, 15, 19,  1, 17])

In [ ]:
# 3.- Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [ ]:
arr3 = np.round(np.random.uniform(1, 20, (4, 6)), 2)

In [31]:
arr3

array([[18.27, 16.36, 11.07, 18.4 , 13.7 , 17.56],
       [19.99, 10.58,  3.8 ,  6.51, 15.2 ,  5.51],
       [10.17,  1.19, 16.56,  7.11, 16.09, 17.1 ],
       [ 1.98, 19.04,  4.77, 15.28, 10.24,  2.98]])

In [32]:
arr3[3]

array([ 1.98, 19.04,  4.77, 15.28, 10.24,  2.98])

In [ ]:
# 1.- Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [33]:
arr4 = np.random.rand(2, 3, 5)

In [34]:
arr4

array([[[0.33265466, 0.84192916, 0.7194957 , 0.51421167, 0.49070844],
        [0.27162849, 0.62423863, 0.97458126, 0.74930526, 0.46945702],
        [0.0934034 , 0.90750955, 0.98225635, 0.58297065, 0.457064  ]],

       [[0.91221241, 0.42955551, 0.45702561, 0.06034585, 0.09235886],
        [0.27802242, 0.72168293, 0.74745374, 0.64313736, 0.17522163],
        [0.81968751, 0.65799733, 0.0706545 , 0.88604146, 0.84175159]]])

In [35]:
arr4 = np.round(np.random.rand(2, 3, 5), 1)

In [36]:
arr4

array([[[0.5, 0.8, 1. , 0.8, 0.2],
        [0.7, 0.9, 0.1, 0.9, 0.9],
        [0.8, 0.2, 0.5, 0. , 0.5]],

       [[0.7, 0.8, 0.6, 0.2, 0.1],
        [0.4, 0.3, 0.4, 0.8, 0.6],
        [0.3, 0.3, 0.3, 0.6, 0.2]]])

In [ ]:
# 2.- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

# Si el valor del array es igual que la media, se reemplaza por "A":

In [56]:
arr_vacio = np.empty((2, 3, 5))

In [57]:
arr_vacio

array([[[0.5, 0.8, 1. , 0.8, 0.2],
        [0.7, 0.9, 0.1, 0.9, 0.9],
        [0.8, 0.2, 0.5, 0. , 0.5]],

       [[0.7, 0.8, 0.6, 0.2, 0.1],
        [0.4, 0.3, 0.4, 0.8, 0.6],
        [0.3, 0.3, 0.3, 0.6, 0.2]]])

In [60]:
media = np.round(np.mean(arr_vacio), 1)

In [61]:
media

0.5

In [62]:
reemplazo_media = np.where(arr_vacio == media, "A", arr_vacio)

In [63]:
reemplazo_media

array([[['A', '0.8', '1.0', '0.8', '0.2'],
        ['0.7', '0.9', '0.1', '0.9', '0.9'],
        ['0.8', '0.2', 'A', '0.0', 'A']],

       [['0.7', '0.8', '0.6', '0.2', '0.1'],
        ['0.4', '0.3', '0.4', '0.8', '0.6'],
        ['0.3', '0.3', '0.3', '0.6', '0.2']]], dtype='<U32')

In [ ]:
# Si el valor del array es mayor que la media, se reemplaza por "B".

In [64]:
reemplazo_media2 = np.where(arr_vacio == media, "A", arr_vacio), np.where(arr_vacio > media, "B", arr_vacio)

In [65]:
reemplazo_media2

(array([[['A', '0.8', '1.0', '0.8', '0.2'],
         ['0.7', '0.9', '0.1', '0.9', '0.9'],
         ['0.8', '0.2', 'A', '0.0', 'A']],
 
        [['0.7', '0.8', '0.6', '0.2', '0.1'],
         ['0.4', '0.3', '0.4', '0.8', '0.6'],
         ['0.3', '0.3', '0.3', '0.6', '0.2']]], dtype='<U32'),
 array([[['0.5', 'B', 'B', 'B', '0.2'],
         ['B', 'B', '0.1', 'B', 'B'],
         ['B', '0.2', '0.5', '0.0', '0.5']],
 
        [['B', 'B', 'B', '0.2', '0.1'],
         ['0.4', '0.3', '0.4', 'B', 'B'],
         ['0.3', '0.3', '0.3', 'B', '0.2']]], dtype='<U32'))

In [ ]:
# Si el valor del array es menor que la media, se reemplaza por "C".

In [66]:
reemplazo_media3 = np.where(arr_vacio == media, "A", arr_vacio), np.where(arr_vacio > media, "B", arr_vacio), np.where (arr_vacio < media, "C", arr_vacio)

In [67]:
reemplazo_media3

(array([[['A', '0.8', '1.0', '0.8', '0.2'],
         ['0.7', '0.9', '0.1', '0.9', '0.9'],
         ['0.8', '0.2', 'A', '0.0', 'A']],
 
        [['0.7', '0.8', '0.6', '0.2', '0.1'],
         ['0.4', '0.3', '0.4', '0.8', '0.6'],
         ['0.3', '0.3', '0.3', '0.6', '0.2']]], dtype='<U32'),
 array([[['0.5', 'B', 'B', 'B', '0.2'],
         ['B', 'B', '0.1', 'B', 'B'],
         ['B', '0.2', '0.5', '0.0', '0.5']],
 
        [['B', 'B', 'B', '0.2', '0.1'],
         ['0.4', '0.3', '0.4', 'B', 'B'],
         ['0.3', '0.3', '0.3', 'B', '0.2']]], dtype='<U32'),
 array([[['0.5', '0.8', '1.0', '0.8', 'C'],
         ['0.7', '0.9', 'C', '0.9', '0.9'],
         ['0.8', 'C', '0.5', 'C', '0.5']],
 
        [['0.7', '0.8', '0.6', 'C', 'C'],
         ['C', 'C', 'C', '0.8', '0.6'],
         ['C', 'C', 'C', '0.6', 'C']]], dtype='<U32'))

In [68]:
# Si el valor es igual que el máximo, se reemplaza por "D".

maximo = np.max(arr_vacio)

In [69]:
maximo

1.0

In [71]:
reemplazo_media4 = np.where(arr_vacio == media, "A", arr_vacio), np.where(arr_vacio > media, "B", arr_vacio), np.where (arr_vacio < media, "C", arr_vacio), np.where (arr_vacio == maximo, "D", arr_vacio)

In [72]:
reemplazo_media4

(array([[['A', '0.8', '1.0', '0.8', '0.2'],
         ['0.7', '0.9', '0.1', '0.9', '0.9'],
         ['0.8', '0.2', 'A', '0.0', 'A']],
 
        [['0.7', '0.8', '0.6', '0.2', '0.1'],
         ['0.4', '0.3', '0.4', '0.8', '0.6'],
         ['0.3', '0.3', '0.3', '0.6', '0.2']]], dtype='<U32'),
 array([[['0.5', 'B', 'B', 'B', '0.2'],
         ['B', 'B', '0.1', 'B', 'B'],
         ['B', '0.2', '0.5', '0.0', '0.5']],
 
        [['B', 'B', 'B', '0.2', '0.1'],
         ['0.4', '0.3', '0.4', 'B', 'B'],
         ['0.3', '0.3', '0.3', 'B', '0.2']]], dtype='<U32'),
 array([[['0.5', '0.8', '1.0', '0.8', 'C'],
         ['0.7', '0.9', 'C', '0.9', '0.9'],
         ['0.8', 'C', '0.5', 'C', '0.5']],
 
        [['0.7', '0.8', '0.6', 'C', 'C'],
         ['C', 'C', 'C', '0.8', '0.6'],
         ['C', 'C', 'C', '0.6', 'C']]], dtype='<U32'),
 array([[['0.5', '0.8', 'D', '0.8', '0.2'],
         ['0.7', '0.9', '0.1', '0.9', '0.9'],
         ['0.8', '0.2', '0.5', '0.0', '0.5']],
 
        [['0.7', '0.8', '0.6', '0

In [ ]:
# Si el valor es igual que el mínimo, se reemplaza por "E"

In [75]:
minimo = np.min(arr_vacio)

In [76]:
minimo

0.0

In [77]:
reemplazo_media5 = np.where(arr_vacio == media, "A", arr_vacio), np.where(arr_vacio > media, "B", arr_vacio), np.where (arr_vacio < media, "C", arr_vacio), np.where (arr_vacio == maximo, "D", arr_vacio), np.where (arr_vacio == minimo, "E", arr_vacio)

In [78]:
reemplazo_media5

(array([[['A', '0.8', '1.0', '0.8', '0.2'],
         ['0.7', '0.9', '0.1', '0.9', '0.9'],
         ['0.8', '0.2', 'A', '0.0', 'A']],
 
        [['0.7', '0.8', '0.6', '0.2', '0.1'],
         ['0.4', '0.3', '0.4', '0.8', '0.6'],
         ['0.3', '0.3', '0.3', '0.6', '0.2']]], dtype='<U32'),
 array([[['0.5', 'B', 'B', 'B', '0.2'],
         ['B', 'B', '0.1', 'B', 'B'],
         ['B', '0.2', '0.5', '0.0', '0.5']],
 
        [['B', 'B', 'B', '0.2', '0.1'],
         ['0.4', '0.3', '0.4', 'B', 'B'],
         ['0.3', '0.3', '0.3', 'B', '0.2']]], dtype='<U32'),
 array([[['0.5', '0.8', '1.0', '0.8', 'C'],
         ['0.7', '0.9', 'C', '0.9', '0.9'],
         ['0.8', 'C', '0.5', 'C', '0.5']],
 
        [['0.7', '0.8', '0.6', 'C', 'C'],
         ['C', 'C', 'C', '0.8', '0.6'],
         ['C', 'C', 'C', '0.6', 'C']]], dtype='<U32'),
 array([[['0.5', '0.8', 'D', '0.8', '0.2'],
         ['0.7', '0.9', '0.1', '0.9', '0.9'],
         ['0.8', '0.2', '0.5', '0.0', '0.5']],
 
        [['0.7', '0.8', '0.6', '0

In [79]:
# Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

arr_3d = np.random.randint(0, 101, (2, 3, 5))

In [80]:
arr_3d

array([[[55, 47, 78,  6, 54],
        [32, 17, 29,  8, 82],
        [ 1, 41,  2, 22, 72]],

       [[57, 58, 31, 24, 24],
        [50, 56,  4, 70, 21],
        [ 4, 61, 24, 17,  2]]])

In [85]:
arr_3d.flat[::3] = 0


In [86]:
arr_3d

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0, 58, 31,  0, 24],
        [50,  0,  4, 70,  0],
        [ 4, 61,  0, 17,  2]]])