In [31]:
import numpy as np

In [32]:
# 1.- Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

arr1 = np.random.randint (10, 100, 50)

In [33]:
arr1 = np.arange (10, 100, 5)

In [34]:
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [35]:
# 2.- Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [36]:
arr2 = np.random.randint (1, 21, 30)

In [37]:
arr2

array([ 7, 11, 16, 12, 10, 15, 14, 10, 13, 19, 15, 17, 13,  5, 19,  6, 14,
        8, 19,  4,  2, 19,  9, 20, 19, 13,  2, 16, 13, 10])

In [38]:
impares = arr2 [::2]

In [39]:
impares

array([ 7, 16, 10, 14, 13, 15, 13, 19, 14, 19,  2,  9, 19,  2, 13])

In [40]:
# 3.- Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [41]:
arr3 = np.round(np.random.uniform(1, 20, (4, 6)), 2)

In [42]:
arr3

array([[10.28,  8.81, 19.75,  9.76, 18.3 ,  5.82],
       [10.53,  2.37,  3.22, 16.32, 16.99, 10.19],
       [15.4 , 14.05, 10.73, 16.65, 14.19, 17.4 ],
       [ 3.28, 16.3 , 19.68,  8.93,  8.58,  5.03]])

In [43]:
arr3[3]

array([ 3.28, 16.3 , 19.68,  8.93,  8.58,  5.03])

In [44]:
# 1.- Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [45]:
arr4 = np.random.rand(2, 3, 5)

In [46]:
arr4

array([[[0.51095275, 0.73996532, 0.76679532, 0.53056421, 0.09792277],
        [0.91012164, 0.07573491, 0.03235745, 0.24626138, 0.04972494],
        [0.82763249, 0.61211409, 0.98583998, 0.90796111, 0.56704791]],

       [[0.71593911, 0.96666861, 0.44781604, 0.86720443, 0.18866482],
        [0.57141468, 0.45888454, 0.68444144, 0.21775255, 0.28281407],
        [0.808663  , 0.76628572, 0.99144954, 0.0035794 , 0.6031856 ]]])

In [47]:
arr4 = np.round(np.random.rand(2, 3, 5), 1)

In [48]:
arr4

array([[[0.8, 0.7, 0.9, 1. , 0.4],
        [0.1, 1. , 0.2, 0.6, 1. ],
        [0.4, 0.2, 0.5, 1. , 0.7]],

       [[0.4, 0.1, 0.3, 0.2, 0.3],
        [1. , 0.7, 0.6, 0.9, 0.3],
        [0.6, 0.8, 0.4, 0.6, 0.3]]])

In [49]:
# 2.- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

# Si el valor del array es igual que la media, se reemplaza por "A":

In [50]:
arr_vacio = np.empty((2, 3, 5))

In [51]:
arr_vacio

array([[[0.8, 0.7, 0.9, 1. , 0.4],
        [0.1, 1. , 0.2, 0.6, 1. ],
        [0.4, 0.2, 0.5, 1. , 0.7]],

       [[0.4, 0.1, 0.3, 0.2, 0.3],
        [1. , 0.7, 0.6, 0.9, 0.3],
        [0.6, 0.8, 0.4, 0.6, 0.3]]])

In [52]:
media = np.round(np.mean(arr_vacio), 1)

In [53]:
media

0.6

In [54]:
reemplazo_media = np.where(arr_vacio == media, "A", arr_vacio)

In [55]:
reemplazo_media

array([[['0.8', '0.7', '0.9', '1.0', '0.4'],
        ['0.1', '1.0', '0.2', 'A', '1.0'],
        ['0.4', '0.2', '0.5', '1.0', '0.7']],

       [['0.4', '0.1', '0.3', '0.2', '0.3'],
        ['1.0', '0.7', 'A', '0.9', '0.3'],
        ['A', '0.8', '0.4', 'A', '0.3']]], dtype='<U32')

In [56]:
# Si el valor del array es mayor que la media, se reemplaza por "B".

In [57]:
reemplazo_media2 = np.where(arr_vacio == media, "A", arr_vacio), np.where(arr_vacio > media, "B", arr_vacio)

In [58]:
reemplazo_media2

(array([[['0.8', '0.7', '0.9', '1.0', '0.4'],
         ['0.1', '1.0', '0.2', 'A', '1.0'],
         ['0.4', '0.2', '0.5', '1.0', '0.7']],
 
        [['0.4', '0.1', '0.3', '0.2', '0.3'],
         ['1.0', '0.7', 'A', '0.9', '0.3'],
         ['A', '0.8', '0.4', 'A', '0.3']]], dtype='<U32'),
 array([[['B', 'B', 'B', 'B', '0.4'],
         ['0.1', 'B', '0.2', '0.6', 'B'],
         ['0.4', '0.2', '0.5', 'B', 'B']],
 
        [['0.4', '0.1', '0.3', '0.2', '0.3'],
         ['B', 'B', '0.6', 'B', '0.3'],
         ['0.6', 'B', '0.4', '0.6', '0.3']]], dtype='<U32'))

In [59]:
# Si el valor del array es menor que la media, se reemplaza por "C".

In [76]:
reemplazo_media3 = np.where(arr_vacio == media, "A", arr_vacio), np.where(arr_vacio > media, "B", arr_vacio), np.where (arr_vacio < media, "C", arr_vacio)

In [78]:
# Definir condiciones
condiciones = [
    arr_vacio == media,  # Igual a la media → "A"
    arr_vacio > media,   # Mayor que la media → "B"
    arr_vacio < media    # Menor que la media → "C"
]
# Valores que se asignarán según las condiciones
valores = ["A", "B", "C"]
# Aplicar np.select()
reemplazo_media3 = np.select(condiciones, valores)

In [79]:
reemplazo_media3

array([[['B', 'B', 'B', 'B', 'C'],
        ['C', 'B', 'C', 'A', 'B'],
        ['C', 'C', 'C', 'B', 'B']],

       [['C', 'C', 'C', 'C', 'C'],
        ['B', 'B', 'A', 'B', 'C'],
        ['A', 'B', 'C', 'A', 'C']]], dtype='<U3')

In [62]:
# Si el valor es igual que el máximo, se reemplaza por "D".

maximo = np.max(arr_vacio)

In [63]:
maximo

1.0

In [64]:
reemplazo_media4 = np.where(arr_vacio == media, "A", arr_vacio), np.where(arr_vacio > media, "B", arr_vacio), np.where (arr_vacio < media, "C", arr_vacio), np.where (arr_vacio == maximo, "D", arr_vacio)

In [65]:
reemplazo_media4

(array([[['0.8', '0.7', '0.9', '1.0', '0.4'],
         ['0.1', '1.0', '0.2', 'A', '1.0'],
         ['0.4', '0.2', '0.5', '1.0', '0.7']],
 
        [['0.4', '0.1', '0.3', '0.2', '0.3'],
         ['1.0', '0.7', 'A', '0.9', '0.3'],
         ['A', '0.8', '0.4', 'A', '0.3']]], dtype='<U32'),
 array([[['B', 'B', 'B', 'B', '0.4'],
         ['0.1', 'B', '0.2', '0.6', 'B'],
         ['0.4', '0.2', '0.5', 'B', 'B']],
 
        [['0.4', '0.1', '0.3', '0.2', '0.3'],
         ['B', 'B', '0.6', 'B', '0.3'],
         ['0.6', 'B', '0.4', '0.6', '0.3']]], dtype='<U32'),
 array([[['0.8', '0.7', '0.9', '1.0', 'C'],
         ['C', '1.0', 'C', '0.6', '1.0'],
         ['C', 'C', 'C', '1.0', '0.7']],
 
        [['C', 'C', 'C', 'C', 'C'],
         ['1.0', '0.7', '0.6', '0.9', 'C'],
         ['0.6', '0.8', 'C', '0.6', 'C']]], dtype='<U32'),
 array([[['0.8', '0.7', '0.9', 'D', '0.4'],
         ['0.1', 'D', '0.2', '0.6', 'D'],
         ['0.4', '0.2', '0.5', 'D', '0.7']],
 
        [['0.4', '0.1', '0.3', '0.2', '

In [66]:
# Si el valor es igual que el mínimo, se reemplaza por "E"

In [67]:
minimo = np.min(arr_vacio)

In [68]:
minimo

0.1

In [69]:
reemplazo_media5 = np.where(arr_vacio == media, "A", arr_vacio), np.where(arr_vacio > media, "B", arr_vacio), np.where (arr_vacio < media, "C", arr_vacio), np.where (arr_vacio == maximo, "D", arr_vacio), np.where (arr_vacio == minimo, "E", arr_vacio)

In [70]:
reemplazo_media5

(array([[['0.8', '0.7', '0.9', '1.0', '0.4'],
         ['0.1', '1.0', '0.2', 'A', '1.0'],
         ['0.4', '0.2', '0.5', '1.0', '0.7']],
 
        [['0.4', '0.1', '0.3', '0.2', '0.3'],
         ['1.0', '0.7', 'A', '0.9', '0.3'],
         ['A', '0.8', '0.4', 'A', '0.3']]], dtype='<U32'),
 array([[['B', 'B', 'B', 'B', '0.4'],
         ['0.1', 'B', '0.2', '0.6', 'B'],
         ['0.4', '0.2', '0.5', 'B', 'B']],
 
        [['0.4', '0.1', '0.3', '0.2', '0.3'],
         ['B', 'B', '0.6', 'B', '0.3'],
         ['0.6', 'B', '0.4', '0.6', '0.3']]], dtype='<U32'),
 array([[['0.8', '0.7', '0.9', '1.0', 'C'],
         ['C', '1.0', 'C', '0.6', '1.0'],
         ['C', 'C', 'C', '1.0', '0.7']],
 
        [['C', 'C', 'C', 'C', 'C'],
         ['1.0', '0.7', '0.6', '0.9', 'C'],
         ['0.6', '0.8', 'C', '0.6', 'C']]], dtype='<U32'),
 array([[['0.8', '0.7', '0.9', 'D', '0.4'],
         ['0.1', 'D', '0.2', '0.6', 'D'],
         ['0.4', '0.2', '0.5', 'D', '0.7']],
 
        [['0.4', '0.1', '0.3', '0.2', '

In [71]:
# Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

arr_3d = np.random.randint(0, 101, (2, 3, 5))

In [72]:
arr_3d

array([[[67, 25, 51, 63,  1],
        [35, 79, 43, 46, 44],
        [48, 79, 89, 15, 99]],

       [[ 4, 93,  6, 34, 41],
        [ 8, 67, 77, 10, 64],
        [41, 26, 52, 48,  3]]])

In [73]:
arr_3d.flat[::3] = 0


In [74]:
arr_3d

array([[[ 0, 25, 51,  0,  1],
        [35,  0, 43, 46,  0],
        [48, 79,  0, 15, 99]],

       [[ 0, 93,  6,  0, 41],
        [ 8,  0, 77, 10,  0],
        [41, 26,  0, 48,  3]]])